# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

stages:  
 - stage: Deploy 
   displayName: 'Deploy Node JS in Digital Ocean Server'
   jobs:   
     steps:
     - task: CopyFilesOverSSH@0
       displayName: 'Securely copy files to the remote machine'
       inputs:
         sshEndpoint: 'Digital ocean Connection'
         sourceFolder: Scripts
         targetFolder: '~/'

     - task: SSH@0
       displayName: 'Run shell inline on remote machine'
       inputs:
         sshEndpoint: 'Digital ocean Connection'
         runOptions: inline
         inline: |
          sudo chmod +s git.sh
          chmod +x git.sh
          bash git.sh
   



