# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


stages:  
 - stage: Deploy 
   displayName: 'Deploy Node JS in Digital Ocean Server'
   jobs:  
   - job:
     pool:
      vmImage: 'ubuntu-latest' 
     steps:      
       - task: Docker@2
         displayName: 'Build Image'
         inputs:
           containerRegistry: 'Docker-service-connection'
           repository: 'jilty / digital-ocean-app'
      
       - task: CopyFilesOverSSH@0
         displayName: 'Securely copy files to the remote machine'
         inputs:
           sshEndpoint: 'Digital ocean Connection'
           sourceFolder: Scripts
           targetFolder: '~/'    
       - task: SSH@0
         displayName: 'Run shell inline on remote machine'
         inputs:
           sshEndpoint: 'Digital ocean Connection'
           runOptions: inline
           inline: |
            sudo kill -9 `sudo lsof -t -i:8082`
            docker pull jilty/digital-ocean-app:latest
            docker run -d --network host  jilty/digital-ocean-app:latest    
#      - task: CopyFilesOverSSH@0
#        displayName: 'Securely copy files to the remote machine'
#        inputs:
#          sshEndpoint: 'Digital ocean Connection'
#          sourceFolder: Scripts
#          targetFolder: '~/'

#      - task: SSH@0
#        displayName: 'Run shell inline on remote machine'
#        inputs:
#          sshEndpoint: 'Digital ocean Connection'
#          runOptions: inline
#          inline: |
#           sudo chmod +s git.sh
#           chmod +x git.sh
#           bash git.sh
   



