# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
 
 - powershell: |
   Write-Host "Show all folder content"
   Get-ChildItem -Path $(Agent.WorkFolder)\*.* -Recurse -Force
  errorActionPreference: continue
  displayName: 'PowerShell Script List folder structure'
  continueOnError: true 

- script: |
    npm install 
  displayName: 'npm install and build'
        

  



